### ISSUE TITLE
Mismatch in Metrics calculation for PAT datasource

### ISSUE THREAD

**Issue by Shoaib15khan** [Sunbird-cQube/community#430] opened 2022-10-06 08:19 UTC
There is a mismatch found in the "performance" column calculations in PAT Heatchart and PAT MApreport Gradewise reports.

**Comment by RNarmatha** [comment] 2022-10-14 03:44
@PavitraIR Could you please the status of the ticket and target completion date

**Comment by PavitraIR** [comment] 2022-10-14 03:52
we have found the root cause, I am fixing on it

**Comment by JalajaTR** [comment] 2022-10-15 07:01
Assigning to @Shoaib15khan  for retesting

**Comment by RNarmatha** [comment] 2022-12-14 13:23
Completed

**Closed by RNarmatha** 2022-12-14 13:23 UTC
Labels: Bug-Minor, From-v4.0-Alpha
