### ISSUE TITLE
Azur - admin console Issues

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#632] opened 2022-10-19 07:24 UTC
**Issues:**
**Data Reply**  
- Data source data reply is not working **(Resolved)**
- Data Reply is not working **(Resolved)**
  alert box showing undefined 

-**Configuration** - Diksha summary-rollup Periodic Selection is not working 
- **Summary** **statistics** is not working - **Resolved**
	- processed student attendance file it is not captured in the summary table **(Resolved)**

**Comment by padmanabha1234** [comment] 2022-10-20 08:56
@Sharathnaik38 python code is working please check

**Comment by Sharathnaik38** [comment] 2022-10-20 09:03
@chetandg123 please test the Diksha summary-rollup

**Comment by htvenkatesh** [comment] 2022-10-20 10:26
@chetandg123 can u test this

**Comment by chetandg123** [comment] 2022-10-20 10:57
@htvenkatesh @Sharathnaik38 @padmanabha1234 
completed re-testing of above listed issues are not fixed except summary stastics 

@padmanabha1234 processed records showing 0 in the table for vsk files

**Comment by dhanush-2397** [comment] 2022-10-20 11:28
@chetandg123 data reply is fixed. Please Re-test

**Comment by chetandg123** [comment] 2022-10-20 18:23
@htvenkatesh defect re-testing is not happened due to not being able to enter the admin console dashboard screen 
when we click on the admin console button 
console error:


![Image](https://user-images.githubusercontent.com/64146636/197028136-5171dca4-a6d2-40c5-ba2d-d1b61b567519.png)

**Comment by chetandg123** [comment] 2022-10-21 07:03
@htvenkatesh @pandutibil  

@padmanabha1234 
Data retention is working in UI , after that if started data reply processor once done with that checked in the data base table - data retention meta table is not update with selected retention days 

![Image](https://user-images.githubusercontent.com/64146636/197131540-d09f4c5e-7def-4679-9181-9f482ef37e42.png)

**Comment by devu1454** [comment] 2022-10-25 09:10
1.data reply is not working
2.Diksha summary-rollup Periodic Selection is not working

**Comment by dhanush-2397** [comment] 2022-10-27 09:23
@devu1454 Please re-test Data Replay for Azure.

**Comment by devu1454** [comment] 2022-10-27 12:28
Data Replay/Retention is working as expected. Tested for infrastructure, crc, teacher_attendance and sat

**Comment by devu1454** [comment] 2022-10-27 12:32
Still diksha summary-rollup Periodic Selection is not working

**Comment by dhanush-2397** [comment] 2022-10-27 12:47
@devu1454 For Diksha summary roll up faizan is working with padmanabha regarding few changes.

**Comment by padmanabha1234** [comment] 2022-10-27 12:49
@devu1454 Code is done, once merged please take a re-test on it.

**Comment by chetandg123** [comment] 2022-10-28 08:16
@dhanush-2397 @asifbasha61 we are not able to enter the admin console dashboard please refer below screen shot for reference 


![Image](https://user-images.githubusercontent.com/64146636/198539177-bb183222-a88f-406b-bc01-723082d20102.png)

**Comment by chetandg123** [comment] 2022-11-02 04:55
Task is paused due to dependency of issue #688

**Comment by chetandg123** [comment] 2022-11-02 10:34
Defect re-testing is paused due to issue #656

**Comment by chetandg123** [comment] 2022-11-03 11:29
@htvenkatesh @padmanabha1234 

-Configuration - Diksha summary-rollup Periodic Selection is not working
**From admin console Configuration - Diksha summary-Rollup Periodic Selection is working showing alert pop up as selection successfully , but from nifi - diksha customer transformer is showing running as status but not processing the diksha data file**

**Comment by RNarmatha** [comment] 2022-11-03 11:33
@padmanabha1234 , Please find out root cause for this ticket

**Comment by chetandg123** [comment] 2022-11-04 10:42
@RNarmatha tested through api , summary data file is not picking in nifi so @padmanabha1234  checking on issue

**Comment by RNarmatha** [comment] 2022-11-07 04:34
Azure Related - need to check

**Comment by chetandg123** [comment] 2022-11-07 09:51
Configuration - Diksha Summary - Roll up Periodic Selection is not working (From Admin Console) 

@htvenkatesh @RNarmatha 
Diksha File processing through API is only supporting to s3 (it is working as expected ) but it wont supporting in azure 

@padmanabha1234 please give brief explanation

**Comment by RNarmatha** [comment] 2022-12-14 10:41
Issue is fixed

**Closed by RNarmatha** 2022-12-14 10:41 UTC
Labels: Bug-Major
